# Pandas

In [38]:
import pandas as pd
import numpy as np

In [12]:
s1 = pd.Series([45, 1900, 4470, 2780, 3660, 870], dtype = np.float32)
s1

0      45.0
1    1900.0
2    4470.0
3    2780.0
4    3660.0
5     870.0
dtype: float32

In [13]:
type(s1)

pandas.core.series.Series

In [14]:
s1.name = "series_1"
s1

0      45.0
1    1900.0
2    4470.0
3    2780.0
4    3660.0
5     870.0
Name: series_1, dtype: float32

In [15]:
s1.values

array([  45., 1900., 4470., 2780., 3660.,  870.], dtype=float32)

In [16]:
type(s1.values)

numpy.ndarray

In [17]:
s1.index = ['idx1', 'idx2', 'idx3', 'idx4', 'idx5', 'idx6']
s1

idx1      45.0
idx2    1900.0
idx3    4470.0
idx4    2780.0
idx5    3660.0
idx6     870.0
Name: series_1, dtype: float32

In [18]:
s1 = pd.Series({
                'idx1': 650,
                'idx2': 170,
                'idx3': 10,
                'idx4': 290,
                'idx5': 90,
                'idx6': 78
               }, name ='product_demand')

s1

idx1    650
idx2    170
idx3     10
idx4    290
idx5     90
idx6     78
Name: product_demand, dtype: int64

In [19]:
s1[4]

90

In [22]:
s1['idx5']

90

In [23]:
s1[[3,4]]

idx4    290
idx5     90
Name: product_demand, dtype: int64

In [24]:
s1[['idx1', 'idx6']]

idx1    650
idx6     78
Name: product_demand, dtype: int64

In [25]:
s1 > 30

idx1     True
idx2     True
idx3    False
idx4     True
idx5     True
idx6     True
Name: product_demand, dtype: bool

In [27]:
s1[s1 > 100]

idx1    650
idx2    170
idx4    290
Name: product_demand, dtype: int64

In [29]:
s1[s1 > 100] = 4000

In [30]:
s1

idx1    4000
idx2    4000
idx3      10
idx4    4000
idx5      90
idx6      78
Name: product_demand, dtype: int64

In [31]:
s1.mean()

2029.6666666666667

In [32]:
s1.std()

2158.5644921258818

In [36]:
s1[(s1 > 10) & (s1 < 150)]

idx5    90
idx6    78
Name: product_demand, dtype: int64

In [46]:
import random
import string
random.seed(10)
letters = string.ascii_lowercase
rand_letters = random.choices(letters,k=6)
np.array(rand_letters)

array(['o', 'l', 'p', 'f', 'v', 'v'], dtype='<U1')

In [47]:
df = pd.DataFrame({'colume_1': np.arange(6),
                    'colume_2' : np.linspace(-1, 1, 6),
                    'colume_3' : np.array(rand_letters),
                    'colume_4': [6,4,9,3,2,8]})
df

colume_1  colume_2 colume_3  colume_4
0         0      -1.0        o         6
1         1      -0.6        l         4
2         2      -0.2        p         9
3         3       0.2        f         3
4         4       0.6        v         2
5         5       1.0        v         8

In [48]:
df.index = ['r1', 'r2', 'r3', 'r4', 'r5', 'r6']
df

colume_1  colume_2 colume_3  colume_4
r1         0      -1.0        o         6
r2         1      -0.6        l         4
r3         2      -0.2        p         9
r4         3       0.2        f         3
r5         4       0.6        v         2
r6         5       1.0        v         8

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, r1 to r6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   colume_1  6 non-null      int64  
 1   colume_2  6 non-null      float64
 2   colume_3  6 non-null      object 
 3   colume_4  6 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 240.0+ bytes


In [50]:
df.shape

(6, 4)

In [52]:
df.dtypes

colume_1      int64
colume_2    float64
colume_3     object
colume_4      int64
dtype: object

In [58]:
df.iloc[1,1]

-0.6

In [59]:
df.iloc[1]

colume_1      1
colume_2   -0.6
colume_3      l
colume_4      4
Name: r2, dtype: object

In [61]:
df.iloc[:,1]

r1   -1.0
r2   -0.6
r3   -0.2
r4    0.2
r5    0.6
r6    1.0
Name: colume_2, dtype: float64

In [63]:
np.array(df.iloc[:,1])

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [64]:
df.iloc[:,1].values

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [68]:
df[['colume_2']]

colume_2
r1      -1.0
r2      -0.6
r3      -0.2
r4       0.2
r5       0.6
r6       1.0

In [69]:
df[['colume_2', 'colume_1']]

colume_2  colume_1
r1      -1.0         0
r2      -0.6         1
r3      -0.2         2
r4       0.2         3
r5       0.6         4
r6       1.0         5

In [70]:
df

colume_1  colume_2 colume_3  colume_4
r1         0      -1.0        o         6
r2         1      -0.6        l         4
r3         2      -0.2        p         9
r4         3       0.2        f         3
r5         4       0.6        v         2
r6         5       1.0        v         8

In [78]:
df[['colume_6']] = df[["colume_1"]] *2
df

colume_1  colume_2 colume_3  colume_4  colume_6
r1         0      -1.0        o         6         0
r2         1      -0.6        l         4         2
r3         2      -0.2        p         9         4
r4         3       0.2        f         3         6
r5         4       0.6        v         2         8
r6         5       1.0        v         8        10

In [80]:
df.loc["r2"]

colume_1      1
colume_2   -0.6
colume_3      l
colume_4      4
colume_6      2
Name: r2, dtype: object

# matplotlib